title: Welcome to Elegant Access
description: Elegant Access is a blog that share android development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "elegantaccess.org" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Willy Chen
author-image:   champion.JPG
author-job:     Android Developer
author-email:   championsheeps@gmail.com
author-twitter:
author-linkedin: kuan-chun-chen-3b703216b # Add your twitter account
author-link: kc09401811 # Add your twitter account
about-author:   I am a Android developer focusing on Kotlin and Jetpack Compose development. Always hungry to keep learning.

# Social settings
social-twitter:
social-facebook:
social-github:    KuanChunChen
social-pinterest:
social-instagram:
social-youtube:
social-vk:
social-linkedin: kuan-chun-chen-3b703216b

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: G-TS24BQ2JDT

# Comment Section (Disqus)
disqus-identifier: K.C # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
